language: node_js
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-base
    - ocaml-native-compilers
    - ocaml-compiler-libs
    - ocaml-interp
    - ocaml-base-nox
    - ocaml-nox
    - camlp4
    - camlp4-extra
    - time
    - libgmp-dev
env:
  - FORK_USER=talex5 FORK_BRANCH=containers OPAMYES=true OCAML_VERSION=4.01 PINS="irmin:https://github.com/talex5/irmin.git#0.9.9-notests"
